"%dev":
  quarkus:
    rest-client:
      ex-change-client:
        url: https://v6.exchangerate-api.com
        api-key: ${EXCHANGE_API_KEY:912bb8d2c776caf488beeeed}
        connect-timeout: 5000 # 5 seconds to establish the connection
        read-timeout: 10000 # 10 seconds to read the response
        scope: jakarta.inject.Singleton # Scope for the REST client
    log:
      level: INFO
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      category:
        "org.bruno.product":
          level: DEBUG # Logs from your application
        "org.bruno.product.infrastructure.client":
          level: DEBUG # Logs from the REST client
        "io.quarkus.rest.client":
          level: DEBUG # Internal logs from the REST client
        "org.jboss.resteasy.reactive.client":
          level: DEBUG # Detailed debugging (request/response)
    datasource:
      db-kind: postgresql
      username: root
      password: pwd
      jdbc:
        url: jdbc:postgresql://localhost:5434/shopping-cart
      reactive:
        url: postgresql://localhost:5434/shopping-cart
    hibernate-orm:
      log:
        sql: false
      database:
        default-schema: shopping_cart
    liquibase:
      migrate-at-start: true
      default-schema-name: shopping_cart
      liquibase-schema-name: public
